
places = {
  'hobitton': {'lon': -120.717772, 'lat': -54.54657},
  'tuckburrow':  {'lon': -123.662108, 'lat': -56.728623},
  'shire': {'lon': -117.553711, 'lat': -56.776808},
  'tom bombadil':  {'lon': -114.213867, 'lat': -57.30279 },
  'bree':  {'lon': -110.52246, 'lat': -54.007769},
  'thranduils palace':  {'lon': -55.678711, 'lat':  -48.57479},
  'minas tirith':  {'lon': -60.820312, 'lat': -74.566736},
  'iron hills':  {'lon': -21.357422, 'lat': -47.398349},
  'rivendel':  {'lon': -92.768555, 'lat': -53.435719},
  'caradhas':  {'lon': -91.318359, 'lat': -59.01794},
  'moria door':  {'lon': -94.306641, 'lat': -61.689872},
  'moria exit':  {'lon': -80.947266, 'lat': -63.114638},
  'lorien':  {'lon': -21.357422, 'lat': -47.398349},
  'isengard':  {'lon': -93.515625, 'lat': -70.140364},
  'weathertop':  {'lon': -104.150391, 'lat': -52.722986},
  'last bridge':  {'lon': -99.052734, 'lat': -53.252069},
}


options = {}
options['rounds'] = {
  1: {
    'frodo': places['hobitton'],
    'merry': places['hobitton'],
    'sam': places['tuckburrow'],
    'pippin': places['tuckburrow'],
    'gandalf': places['hobitton'],
    'arangorn': places['bree'],
    'legolas': places['thranduils palace'],
    'gimli': places['iron hills'],
    'boromir': places['minas tirith'],
  },
  3: {
    'frodo': places['shire'],
    'merry': places['shire'],
    'sam': places['shire'],
    'pippin': places['shire'],
  },
  9: {
    'frodo': places['tom bombadil'],
    'merry': places['tom bombadil'],
    'sam': places['tom bombadil'],
    'pippin': places['tom bombadil'],
  },
  12: {
    'gandalf': places['isengard'],
    'boromir': places['minas tirith'],
  },
  15: {
    'frodo': places['bree'],
    'merry': places['bree'],
    'sam': places['bree'],
    'pippin': places['bree'],
    'arangorn': places['bree'],
  },
  25: {
    'frodo': places['weathertop'],
    'merry': places['weathertop'],
    'sam': places['weathertop'],
    'pippin': places['weathertop'],
    'arangorn': places['weathertop'],
  },
  28: {
    'frodo': places['last bridge'],
    'merry': places['last bridge'],
    'sam': places['last bridge'],
    'pippin': places['last bridge'],
    'arangorn': places['last bridge'],
    'legolas': places['rivendel'],
  },
  32: {
    'frodo': places['rivendel'],
    'merry': places['rivendel'],
    'sam': places['rivendel'],
    'pippin': places['rivendel'],
  },
  35: {
    'gandalf': places['isengard'],
    'gimli': places['rivendel'],
  },
  40: {
    'boromir': places['rivendel'],
  },
  50: {
    'frodo': places['rivendel'],
    'merry': places['rivendel'],
    'sam': places['rivendel'],
    'pippin': places['rivendel'],
    'gandalf': places['rivendel'],
    'arangorn': places['rivendel'],
    'gimli': places['rivendel'],
    'boromir': places['rivendel'],
    'legolas': places['rivendel'],
  },
  55: {
    'frodo': places['rivendel'],
    'merry': places['rivendel'],
    'sam': places['rivendel'],
    'pippin': places['rivendel'],
    'gandalf': places['rivendel'],
    'arangorn': places['rivendel'],
    'gimli': places['rivendel'],
    'boromir': places['rivendel'],
    'legolas': places['rivendel'],
  },
  60: {
    'frodo': places['caradhas'],
    'merry': places['caradhas'],
    'sam': places['caradhas'],
    'pippin': places['caradhas'],
    'gandalf': places['caradhas'],
    'arangorn': places['caradhas'],
    'gimli': places['caradhas'],
    'boromir': places['caradhas'],
    'legolas': places['caradhas'],
  },
  63: {
    'frodo': places['moria door'],
    'merry': places['moria door'],
    'sam': places['moria door'],
    'pippin': places['moria door'],
    'gandalf': places['moria door'],
    'arangorn': places['moria door'],
    'gimli': places['moria door'],
    'boromir': places['moria door'],
    'legolas': places['moria door'],
  },
  66: {
    'frodo': places['moria exit'],
    'merry': places['moria exit'],
    'sam': places['moria exit'],
    'pippin': places['moria exit'],
    'gandalf': places['moria exit'],
    'arangorn': places['moria exit'],
    'gimli': places['moria exit'],
    'boromir': places['moria exit'],
    'legolas': places['moria exit'],
  },
  68: {
    'frodo': places['lorien'],
    'merry': places['lorien'],
    'sam': places['lorien'],
    'pippin': places['lorien'],
    'gandalf': places['moria exit'],
    'arangorn': places['lorien'],
    'gimli': places['lorien'],
    'boromir': places['lorien'],
    'legolas': places['lorien'],
  },
}
options['last_round'] = 100

